### ISSUE TITLE
Times out, is it launched?

### ISSUE THREAD

**Issue by cryptomeow** [JASchilz/docs.2fa.horse#1]
Good idea! I couldn't find another medium so sorry if out of place, but have you launched this service?
I tried the curl way and it times out.

**Comment by JASchilz** [comment]
Well, that's embarrassing. I neglected to update the documentation from http to https. :(

If you try it now, with https, then you should get a response. It will reject the 555 number as invalid, but I might modify the server to let it accept that number for demonstration purposes.

**Comment by JASchilz** [comment]
OK. I've now also got a fix for the 555 number. Following the documentation exactly will produce:

```
HTTP/1.1 400 BAD REQUEST
Server: nginx/1.10.3
Date: Sat, 01 Dec 2018 16:17:47 GMT
Content-Type: text/json; charset=utf-8
Content-Length: 219
Connection: keep-alive

{
  "cause": "Tummy Tutone",
  "detail": "You've used the number from the documentation, and we're
             so happy about that, but we can't actually send to this number.
             Please enter a real phone number, in the same format."
}
```

I think that's sufficiently helpful.
